#!/usr/bin/env python3
"""
Wallpaper Converter for HuTaOS
Converts PNG/JPG image to VGA Mode 13h compatible C header file.

VGA Mode 13h specs:
- Resolution: 320x200
- Colors: 256 (using 6x6x6 color cube + 16 EGA + 24 grayscale)

Usage:
    python convert_wallpaper.py <input_image> [output_header]

Example:
    python convert_wallpaper.py wallpaper.png ../src/header/graphics/wallpaper.h
"""

import sys
from PIL import Image
import os

# VGA palette definition (matches graphics.c initialization)
def build_vga_palette():
    """Build the VGA 256-color palette as used in graphics_initialize()"""
    palette = []
    
    # First 16 colors - EGA compatibility (using 6-bit values scaled to 8-bit)
    ega_colors = [
        (0, 0, 0),       # 0: Black
        (0, 0, 170),     # 1: Blue
        (0, 170, 0),     # 2: Green
        (0, 170, 170),   # 3: Cyan
        (170, 0, 0),     # 4: Red
        (170, 0, 170),   # 5: Magenta
        (170, 85, 0),    # 6: Brown
        (170, 170, 170), # 7: Light Gray
        (85, 85, 85),    # 8: Dark Gray
        (85, 85, 255),   # 9: Light Blue
        (85, 255, 85),   # 10: Light Green
        (85, 255, 255),  # 11: Light Cyan
        (255, 85, 85),   # 12: Light Red
        (255, 85, 255),  # 13: Light Magenta/Pink
        (255, 255, 85),  # 14: Yellow
        (255, 255, 255), # 15: White
    ]
    palette.extend(ega_colors)
    
    # Colors 16-231: 6x6x6 color cube (216 colors)
    for r in range(6):
        for g in range(6):
            for b in range(6):
                red = int(r * 255 / 5)
                green = int(g * 255 / 5)
                blue = int(b * 255 / 5)
                palette.append((red, green, blue))
    
    # Colors 232-255: Grayscale ramp (24 shades)
    for i in range(1, 24):
        gray = int(i * 255 / 23)
        palette.append((gray, gray, gray))
    
    # Pad to 256 colors
    while len(palette) < 256:
        palette.append((0, 0, 0))
    
    return palette

def find_closest_color(r, g, b, palette):
    """Find the closest color in the VGA palette"""
    min_dist = float('inf')
    best_idx = 0
    
    for idx, (pr, pg, pb) in enumerate(palette):
        # Use weighted Euclidean distance (human eye is more sensitive to green)
        dist = ((r - pr) * 0.299) ** 2 + ((g - pg) * 0.587) ** 2 + ((b - pb) * 0.114) ** 2
        if dist < min_dist:
            min_dist = dist
            best_idx = idx
    
    return best_idx

def convert_image(input_path, output_path):
    """Convert image to VGA Mode 13h compatible C header"""
    
    print(f"Loading image: {input_path}")
    img = Image.open(input_path)
    
    # Convert to RGB if necessary
    if img.mode != 'RGB':
        img = img.convert('RGB')
    
    original_size = img.size
    print(f"Original size: {original_size[0]}x{original_size[1]}")
    
    # Resize to 320x200 using high-quality Lanczos resampling
    target_size = (320, 200)
    img = img.resize(target_size, Image.LANCZOS)
    print(f"Resized to: {target_size[0]}x{target_size[1]}")
    
    # Build VGA palette
    palette = build_vga_palette()
    print(f"Built VGA palette with {len(palette)} colors")
    
    # Convert pixels
    pixels = list(img.getdata())
    vga_pixels = []
    
    print("Converting pixels to VGA palette...")
    for i, (r, g, b) in enumerate(pixels):
        vga_idx = find_closest_color(r, g, b, palette)
        vga_pixels.append(vga_idx)
        
        # Progress indicator
        if (i + 1) % 10000 == 0:
            print(f"  Processed {i + 1}/{len(pixels)} pixels...")
    
    print(f"Converted {len(vga_pixels)} pixels")
    
    # Generate C header file
    print(f"Writing output to: {output_path}")
    
    # Derive .c file path from header path
    c_output_path = output_path.replace('.h', '_data.c')
    
    # Write header file (just declarations)
    with open(output_path, 'w') as f:
        f.write("/**\n")
        f.write(" * Wallpaper data for HuTaOS\n")
        f.write(f" * Original: {os.path.basename(input_path)} ({original_size[0]}x{original_size[1]})\n")
        f.write(f" * Converted: 320x200 with VGA 256-color palette\n")
        f.write(" * \n")
        f.write(" * Auto-generated by convert_wallpaper.py\n")
        f.write(" */\n\n")
        f.write("#ifndef _WALLPAPER_H\n")
        f.write("#define _WALLPAPER_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("#define WALLPAPER_WIDTH  320\n")
        f.write("#define WALLPAPER_HEIGHT 200\n\n")
        f.write("// Wallpaper pixel data (320x200 = 64000 bytes)\n")
        f.write("// Defined in wallpaper_data.c to avoid multiple definition\n")
        f.write("extern const uint8_t wallpaper_data[64000];\n\n")
        f.write("#endif // _WALLPAPER_H\n")
    
    # Write C source file (actual data)
    print(f"Writing data to: {c_output_path}")
    with open(c_output_path, 'w') as f:
        f.write("/**\n")
        f.write(" * Wallpaper pixel data for HuTaOS\n")
        f.write(f" * Original: {os.path.basename(input_path)} ({original_size[0]}x{original_size[1]})\n")
        f.write(f" * Converted: 320x200 with VGA 256-color palette\n")
        f.write(" * \n")
        f.write(" * Auto-generated by convert_wallpaper.py\n")
        f.write(" */\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("// Wallpaper pixel data (320x200 = 64000 bytes)\n")
        f.write("const uint8_t wallpaper_data[64000] = {\n")
        
        # Write pixel data in rows of 16 values
        for i in range(0, len(vga_pixels), 16):
            row = vga_pixels[i:i+16]
            hex_values = ", ".join(f"0x{v:02X}" for v in row)
            if i + 16 < len(vga_pixels):
                f.write(f"    {hex_values},\n")
            else:
                f.write(f"    {hex_values}\n")
        
        f.write("};\n")
    
    print("Done!")
    print(f"\nGenerated files:")
    print(f"  Header: {output_path}")
    print(f"  Data:   {c_output_path}")
    print(f"\nTo use the wallpaper, include the header and call:")
    print("  graphics_draw_wallpaper();")

def main():
    if len(sys.argv) < 2:
        print("Usage: python convert_wallpaper.py <input_image> [output_header]")
        print("Example: python convert_wallpaper.py wallpaper.png ../src/header/graphics/wallpaper.h")
        sys.exit(1)
    
    input_path = sys.argv[1]
    
    if len(sys.argv) >= 3:
        output_path = sys.argv[2]
    else:
        output_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "src", "header", "graphics", "wallpaper.h"
        )
    
    if not os.path.exists(input_path):
        print(f"Error: Input file '{input_path}' not found")
        sys.exit(1)
    
    convert_image(input_path, output_path)

if __name__ == "__main__":
    main()