/**
 * Wallpaper data for HuTaOS
 * Original: wallpaper.png (1778x1000)
 * Converted: 320x200 with VGA 256-color palette
 * 
 * Auto-generated by convert_wallpaper.py
 */

#ifndef _WALLPAPER_H
#define _WALLPAPER_H

#include <stdint.h>
#include <stdbool.h>

#define WALLPAPER_WIDTH  320
#define WALLPAPER_HEIGHT 200
#define WALLPAPER_SIZE   (WALLPAPER_WIDTH * WALLPAPER_HEIGHT)
#define WALLPAPER_NAME_MAX 32

// Maximum number of wallpapers supported
#define WALLPAPER_MAX_COUNT 4

// Wallpaper info structure
typedef struct {
    const uint8_t *data;    // Pointer to pixel data
    const char *name;       // Wallpaper name
} WallpaperInfo;

// Wallpaper pixel data arrays (320x200 = 64000 bytes each)
// Defined in wallpaper_data.c
extern const uint8_t wallpaper_black[64000];

// Current active wallpaper index
extern uint32_t current_wallpaper_index;

// Wallpaper management functions
void wallpaper_init(void);
uint32_t wallpaper_get_count(void);
uint32_t wallpaper_get_current(void);
bool wallpaper_set_current(uint32_t index);
const char* wallpaper_get_name(uint32_t index);
const uint8_t* wallpaper_get_data(uint32_t index);
const uint8_t* wallpaper_get_current_data(void);

// Load wallpaper bytes from filesystem
// Returns 0 on success, non-zero on failure
int wallpaper_load_from_fs(uint32_t parent_inode, const char *filename);

#endif // _WALLPAPER_H
